### ISSUE TITLE
Accidental removal of paragraphs about mathematics

### ISSUE THREAD

**Issue by PabRod** [parallelwindfarms/cylinder#12]
Commit eedcea4cd8196369c23553dc8a64c392fac8dc8e destroys most of my expanded descriptions of the underlying mathematical concepts. Was this deliberate?

**Comment by jhidding** [comment]
Definitely not! Can you restore it yourself?

**Comment by PabRod** [comment]
That was my guess. Yes, I think I can recover it.

**Comment by PabRod** [comment]
Commit 1a7f6f7 reverts the damages.
