### ISSUE TITLE
Cannot enable OpenFOAM in GitHub actions

### ISSUE THREAD

**Issue by PabRod** [parallelwindfarms/cylinder#16]
## Problem

The step of enabling OpenFOAM is failing. The file `/usr/lib/openfoam/openfoam2106/etc/bashrc` is present and [looks good](https://github.com/parallelwindfarms/cylinder/runs/4236237479?check_suite_focus=true). But when trying to execute it, we get an obscure message:

```sh
Error: Process completed with exit code 1.
```

I've tried `chmod +x`, but it is [not allowed](https://github.com/parallelwindfarms/cylinder/runs/4236478056?check_suite_focus=true).

## Possible solution

Why not go back to the containerized version of OpenFOAM?

```sh
on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    container: openfoamplus/of_v1906_centos73 # <------
    name: A job to test OpenFOAM
    steps:
```

**Comment by jhidding** [comment]
Then we're back to the problem that Centos has antient packages. Maybe the command is failing because it is executed using `sh` instead of `bash`? (see https://github.community/t/declaring-a-default-shell-and-environment-variables-across-all-steps-in-a-job-github-actions/16228/2 on howto change that)

**Comment by PabRod** [comment]
I've tried that. But still fails.

**Comment by PabRod** [comment]
Finally we solved it the hacky way:

```sh
    - name: Run tests
      id: run-tests
      run: |
        set +o pipefail
        source /usr/lib/openfoam/openfoam2106/etc/bashrc
        poetry run pytest
      shell: bash
```
